# Generated by Django 3.0.7 on 2020-06-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article_tag_mapping',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='article_tag_mapping',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='article_id',
            new_name='article',
        ),
    ]
