# Generated by Django 3.0.7 on 2020-06-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-updated_at']},
        ),
    ]
