# Generated by Django 3.0.7 on 2020-06-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200614_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
