# Generated by Django 3.0.7 on 2020-06-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200618_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-updated_at',)},
        ),
    ]
