# Generated by Django 3.0.7 on 2020-06-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200618_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user',
            new_name='userID',
        ),
    ]
