# Generated by Django 3.0.7 on 2020-06-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articles_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article_Tag_Mapping',
            new_name='ArticleTagMapping',
        ),
    ]
